Netflox/Controllers/ActorsController.cs
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.IO;
using System.Linq;
using System.Net;
using System.Security.Authentication;
using System.Security.Cryptography.X509Certificates;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Netflox.Models;
using Netflox.ViewModels;
using static System.Net.WebRequestMethods;

namespace Netflox.Controllers
{
    public class ActorsController : Controller
    {
        private readonly Context _context;

        public ActorsController(Context context)
        {
            _context = context;
        }

        // GET: Actors
        public IActionResult Index(int pagina = 1)
        {
            var cantidadRegistrosPorPagina = 10;
            var actores = _context.Actors.OrderBy(x => x.ActorName).Skip((pagina - 1) * cantidadRegistrosPorPagina).Take(cantidadRegistrosPorPagina).ToList();
            var totalDeRegistros = _context.Actors.Count();
            var modelo = new ViewActor
            {
                Actors = actores,
                PaginaActual = pagina,
                TotalDeRegistros = totalDeRegistros,
                RegistrosPorPagina = cantidadRegistrosPorPagina
            };

            ViewData["partial"] = modelo;
            if (modelo.TotalDeRegistros > cantidadRegistrosPorPagina)
            {
                ViewBag.pie = true;
            }
            else { ViewBag.pie = false; }

            return View(modelo.Actors.ToList());

  //          return View(await _context.Actors.ToListAsync());
        }

        // GET: Actors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                .FirstOrDefaultAsync(m => m.ActorId == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // GET: Actors/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Actors/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ActorId,ActorName,Birthdate,PicName")] Actor actor, IFormFile Imagen)
        {
            if (ModelState.IsValid)
            {
                if (Imagen != null)
                {
                    var fichero = Path.GetFileName(Imagen.FileName);
                    actor.PicName = fichero;
                    var ftpserver = new UploadFile("uploadimages", "proyecto3", "ftp://anonvpn.net/");
                    byte[] FileToDB = await ftpserver.sendfileAsync(fichero, Imagen);
                    if (FileToDB != null) { actor.Pc = FileToDB; }
                }
                _context.Add(actor);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        // GET: Actors/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors.FindAsync(id);
            if (actor == null)
            {
                return NotFound();
            }
            return View(actor);
        }

        // POST: Actors/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ActorId,ActorName,Birthdate,PicName")] Actor actor, IFormFile Imagen)
        {
            if (id != actor.ActorId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Entry(actor).State = EntityState.Modified;
                if (Imagen != null)
                {
                    var fichero = Path.GetFileName(Imagen.FileName);
                    actor.PicName = fichero;
                    var ftpserver = new UploadFile("uploadimages", "proyecto3", "ftp://anonvpn.net/" );
                    byte [] FileToDB = await ftpserver.sendfileAsync(fichero, Imagen);
                    if (FileToDB != null) { actor.Pc = FileToDB; }
  
                }
                else
                {

                    _context.Entry(actor).Property(x => x.Pc).IsModified = false;
                    _context.Entry(actor).Property(x => x.PicName).IsModified = false;

                }
                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ActorExists(actor.ActorId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(actor);
        }

        private Task UploadFile(string v)
        {
            throw new NotImplementedException();
        }

        // GET: Actors/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var actor = await _context.Actors
                .FirstOrDefaultAsync(m => m.ActorId == id);
            if (actor == null)
            {
                return NotFound();
            }

            return View(actor);
        }

        // POST: Actors/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {

            var actor = await _context.Actors.FindAsync(id);
            var movies =  _context.Movies.Include(z => z.ActorsLink).Where(x => x.ActorsLink.FirstOrDefault(y => y.ActorId == id).ActorId == id).ToList();
            foreach (var movie in movies)
            {
               var movieActor = movie.ActorsLink.FirstOrDefault(at => at.ActorId == id);
                movie.ActorsLink.Remove(movieActor);

            }

            
            _context.Actors.Remove(actor);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ActorExists(int id)
        {
            return _context.Actors.Any(e => e.ActorId == id);
        }
    }
}

Netflox/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Linq.Expressions;
using System.Net;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting.Server;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Netflox.Models;
using Netflox.ViewModels;
using static System.Net.Mime.MediaTypeNames;

namespace Netflox.Controllers
{
    public class MoviesController : Controller
    {
        private readonly Context _context;

        public string ImageUrl { get; private set; }

        public MoviesController(Context context)
        {
            _context = context;
        }

        // GET: Movies
        public async Task<IActionResult> Index(int pagina = 1)
        {
            var cantidadRegistrosPorPagina = 10;
            var movies = _context.Movies.OrderBy(x => x.Name).Skip((pagina - 1) * cantidadRegistrosPorPagina).Take(cantidadRegistrosPorPagina).ToList();
            var totalDeRegistros = _context.Movies.Count();
            var modelo = new ViewMovie
            {
                Movies = movies,
                PaginaActual = pagina,
                TotalDeRegistros = totalDeRegistros,
                RegistrosPorPagina = cantidadRegistrosPorPagina
            };

            ViewData["partial"] = modelo;
            if (modelo.TotalDeRegistros > cantidadRegistrosPorPagina) {
                ViewBag.pie = true;
            } else { ViewBag.pie = false; }
            

            return View(modelo.Movies.ToList());

        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.MovieId == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MovieId,Name,Director,PicName,Pic")] Movie movie, IFormFile Imagen, IFormFile Video)
        {
            if (ModelState.IsValid)
            {
                if (Imagen != null)
                {
                        var fichero = Path.GetFileName(Imagen.FileName);
                        movie.PicName = fichero;
                    var ftpserver = new UploadFile("uploadimages", "proyecto3", "ftp://anonvpn.net/");
                    byte[] FileToDB = await ftpserver.sendfileAsync(fichero, Imagen);
                    if (FileToDB != null) { movie.Pc = FileToDB; }
                }

                if (Video != null)
                {
                    var nombrefichero = Path.GetFileName(Video.FileName);
                    movie.VideoName = nombrefichero;
                    var ftpserver = new UploadFile("uploadvideos", "proyecto3", "ftp://anonvpn.net/");
                    byte[] FileToDB = await ftpserver.sendfileAsync(nombrefichero, Video);
                    if (FileToDB != null) { movie.Vd = FileToDB; }
                }

                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {

            if (id == null)
            {
                return NotFound();
            }


            var movie = await _context.Movies.FindAsync(id);

            if (movie == null)
            {
                return NotFound();
            } else {
                // Init the actors list
                ViewBag.ActorId = (from actores in _context.Actors
                                   where actores.MoviesLink.All(c => c.MovieId != id)
                                   select actores).ToList();

            }
            return View(movie);
        }

        public async Task<PartialViewResult> ActorsList(int? id, int? actorId)
        {
            if (id != null)
            {
                var movie = await _context.Movies.FirstOrDefaultAsync(x => x.MovieId == id);
                if (actorId != null)
                {
                    //If it is not null we are adding an actor to the movie
                    Actor actor = await _context.Actors.FirstOrDefaultAsync(x => x.ActorId == actorId);

                    _context.Movies.Attach(movie);
                    movie.ActorsLink.Add(new MovieActor(actor));

                    await _context.SaveChangesAsync();

                }
                var actorslist = (from actores in _context.Actors
                                  where actores.MoviesLink.Any(c => c.MovieId == id)
                                  select actores).ToList();
                if (actorslist.Count == 0) {
                    return null;
                } else {
                    ViewBag.MovieId = id;
                    return PartialView("_Actorslist", actorslist);
                }
            } else { return null; }
        }

        public async Task<PartialViewResult> RemoveActor(int id, int? movieId)
        {
            var actor = await _context.Actors.Include(x=>x.MoviesLink).FirstOrDefaultAsync(x => x.ActorId == id);

            var movieActor = actor.MoviesLink.FirstOrDefault(at => at.MovieId == movieId);
            actor.MoviesLink.Remove(movieActor);

            await _context.SaveChangesAsync();
            var actorslist = (from actores in _context.Actors
                              where actores.MoviesLink.Any(c => c.MovieId == movieId)
                              select actores).ToList();
            ViewBag.MovieId = movieId;
            return PartialView("_Actorslist", actorslist);
        }


        //Play: Movies/Play/5
        public async Task<IActionResult> Play(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies.FindAsync(id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }



        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind(include:"MovieId,Name,Director,Pic,PicName,Video,VideoName")] Movie movie, IFormFile Imagen, IFormFile Video)
        {
            if (id != movie.MovieId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                _context.Entry(movie).State = EntityState.Modified;
                if (Imagen != null)
                {
                    var fichero = Path.GetFileName(Imagen.FileName);
                    movie.PicName = fichero;
                    var ftpserver = new UploadFile("uploadimages", "proyecto3", "ftp://anonvpn.net/");
                    byte[] FileToDB = await ftpserver.sendfileAsync(fichero, Imagen);
                    if (FileToDB != null) { movie.Pc = FileToDB; }
                } else
                {
                    _context.Entry(movie).Property(x => x.PicName).IsModified = false;
                    _context.Entry(movie).Property( x => x.Pc).IsModified = false;
;
                   
                }

                if (Video != null)
                {
                    var nombrefichero = Path.GetFileName(Video.FileName);
                    movie.VideoName = nombrefichero;
                    var ftpserver = new UploadFile("uploadvideos", "proyecto3", "ftp://anonvpn.net/");
                    byte[] FileToDB = await ftpserver.sendfileAsync(nombrefichero, Video);
    //                if (FileToDB != null) { movie.Vd = FileToDB; }
                } else
                {
                    _context.Entry(movie).Property(x => x.VideoName).IsModified = false;
                    _context.Entry(movie).Property(x => x.Vd).IsModified = false;
                }

                try
                {
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.MovieId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movies
                .FirstOrDefaultAsync(m => m.MovieId == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            
            var movieBorrar = await _context.Movies.FindAsync(id);
            

Netflox/Views/Shared/_ActorsList.cshtml
@model IEnumerable<Netflox.Models.Actor>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ActorName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PicName)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ActorName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.PicName)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.ActorId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.ActorId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.ActorId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

Netflox/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Netflox</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/css/bootstrap-select.min.css">
    <link href="https://vjs.zencdn.net/7.2.4/video-js.css" rel="stylesheet">
    <script src="https://vjs.zencdn.net/7.2.4/video.js"></script>

</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Netflox</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Actors" asp-action="Index">Actors</a></li>
                    <li><a asp-area="" asp-controller="Movies" asp-action="Index">Movies</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Netflox</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.2/js/bootstrap-select.min.js"></script>
    


    @RenderSection("Scripts", required: false)
</body>
</html>

Netflox/Views/Shared/_paginador.cshtml
@model BaseModelo

@{
    var cantidadPaginas = (int)Math.Ceiling((double)Model.TotalDeRegistros / Model.RegistrosPorPagina);
}

<!--Funcionalidad: Anterior y siguiente-->

<ul class="pagination">
    @if (Model.PaginaActual == 1)
    {
    
        <li class="disabled">@Html.ActionLink("Previous", null, new { pagina = 1 })</li>
    }
    else
    {
      
        <li>@Html.ActionLink("Previous", null, new { pagina = Model.PaginaActual - 1 })</li>
    }

    @if (Model.PaginaActual == cantidadPaginas)
    {

        <li class="disabled">@Html.ActionLink("Next", null, new {pagina = cantidadPaginas })</li>
    }
    else
    {
        <li>@Html.ActionLink("Next", null, new { pagina = Model.PaginaActual + 1 })</li>
    }
</ul>

<!--Funcionalidad: Páginas-->

@{
    int Inicial = 1;
    var radio = 3;
    var cantidadMaximaDePaginas = radio * 2 + 1;
    int Final = (cantidadPaginas > cantidadMaximaDePaginas) ? cantidadMaximaDePaginas : cantidadPaginas;
    if (Model.PaginaActual > radio + 1)
    {
        Inicial = Model.PaginaActual - radio;
        if (cantidadPaginas > Model.PaginaActual + radio)
        {
            Final = Model.PaginaActual + radio;
        }
        else
        {
            Final = cantidadPaginas;
        }
    }
}


<ul class="pagination">
    
    <li>@Html.ActionLink("First", null, new { pagina = 1})</li>
    @for (int i = Inicial; i <= Final; i++)
    {
        if (i == Model.PaginaActual)
        {
            <li class="active">@Html.ActionLink(i.ToString(), null, new { pagina = i })</li>
        }
        else
        {
            <li>@Html.ActionLink(i.ToString(), null, new { pagina = i })</li>
        }
    }
    <li>@Html.ActionLink("Last", null, new  { pagina = cantidadPaginas })</li>
</ul>